spring.application.name=demo
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=student
spring.datasource.password=student
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8081
# setari sa nu modifice tabela si sa afiseze SQL in consola
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true